# This workflow will install Python dependencies and check formatting with Ruff

name: Type check with mypy

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    python-version: "3.10"

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ python-version }}
    - name: Setup environment
      run: |
        make setup
    - name: Check types with mypy
      run: |
        make type
